(()=>{
const NAME='KoffyKraftRoastbooks',VERSION=1;
const STORES=['roasts','plans','captures'];
function open(){return new Promise((resolve,reject)=>{const r=indexedDB.open(NAME,VERSION);r.onupgradeneeded=()=>{const db=r.result;for(const s of STORES)if(!db.objectStoreNames.contains(s))db.createObjectStore(s,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(new Error('Database blocked'))})}
async function put(store,value){const db=await open();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).put(value);tx.oncomplete=()=>resolve(value);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}finally{db.close()}}
async function all(store){const db=await open();try{return await new Promise((resolve,reject)=>{const q=db.transaction(store,'readonly').objectStore(store).getAll();q.onsuccess=()=>resolve(q.result||[]);q.onerror=()=>reject(q.error)})}finally{db.close()}}
async function get(store,id){const db=await open();try{return await new Promise((resolve,reject)=>{const q=db.transaction(store,'readonly').objectStore(store).get(id);q.onsuccess=()=>resolve(q.result||null);q.onerror=()=>reject(q.error)})}finally{db.close()}}
async function remove(store,id){const db=await open();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}finally{db.close()}}
async function migrateLegacy(){if(localStorage.getItem('kk_db_migrated_v1'))return;try{const old=await new Promise((resolve,reject)=>{const r=indexedDB.open('KoffyKraftTemporaryRoastbook');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onupgradeneeded=()=>{}});for(const store of ['roasts','plans']){if(!old.objectStoreNames.contains(store))continue;const rows=await new Promise((resolve,reject)=>{const q=old.transaction(store,'readonly').objectStore(store).getAll();q.onsuccess=()=>resolve(q.result||[]);q.onerror=()=>reject(q.error)});for(const row of rows)await put(store,row)}old.close()}catch(e){}localStorage.setItem('kk_db_migrated_v1','1')}
async function syncRoast(rec){const t=localStorage.getItem('kk_auth_token');if(!t)return {skipped:true};try{const r=await fetch('/api/roasts',{method:'POST',headers:{'content-type':'application/json','authorization':'Bearer '+t},body:JSON.stringify(rec)});if(!r.ok)return {ok:false,status:r.status};const x=await r.json();const next={...rec,cloud:{syncedAt:new Date().toISOString(),serverId:x.id}};await put('roasts',next);return {ok:true,item:next}}catch(e){return {ok:false,error:String(e)}}}
async function pullRoasts(){const t=localStorage.getItem('kk_auth_token');if(!t)return {skipped:true,items:[]};try{const r=await fetch('/api/roasts',{headers:{'authorization':'Bearer '+t},cache:'no-store'});if(!r.ok)return {ok:false,status:r.status,items:[]};const x=await r.json();const items=x.items||[];for(const item of items)await put('roasts',{...item,cloud:{syncedAt:new Date().toISOString(),serverId:item.serverId||item.id}});return {ok:true,items}}catch(e){return {ok:false,error:String(e),items:[]}}}
window.KKDB={NAME,VERSION,open,put,all,get,remove,migrateLegacy,syncRoast,pullRoasts};
})();