// KoffyKraft record snapshots: a copy of one record, trimmed for sharing (spaces, public profile).
// Shared by share.html and profile.html. The original record is never changed.
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>{const n=parseFloat(v);return Number.isFinite(n)?n:null};const r1=v=>Math.round(v*10)/10;
const fmtD=d=>{const x=new Date(d);return isNaN(x)?'':x.toLocaleString('en-IN',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})};
const KN={green:'Green lot',brew:'Brew',roast:'Roast',cupping:'Cupping',process:'Origin process',note:'Note'};
// ---------- snapshots of my own records (a copy is shared, your record stays yours) ----------
function brewSnap(b){const d=num(b.dose),w=num(b.water),t=num(b.tds);let bev=num(b.beverage);const esp=/espresso|moka/i.test(b.method||'');if(!bev&&w&&d)bev=esp?w:w-2*d;const ey=t&&d&&bev?r1(t*bev/d):null;
 return{title:(b.roastLabel||b.coffee||'Brew')+' · '+(b.method||''),data:{coffee:b.roastLabel||b.coffee||'',method:b.method,brewer:b.brewer,dose:d,water:w,ratio:d&&w?r1(w/d):null,waterTemp:b.waterTemp,grinder:b.grinder,grind:b.grind,bloom:b.bloom,time:b.time,pours:b.pours,waterType:b.waterType,tds:t,ey,restDays:b.restDays!=null?r1(b.restDays):null,rating:b.rating,descriptors:b.descriptors,notes:b.notes,brewedAt:b.brewedAt}}}
function cupSnap(c){return{title:'Cupping · '+(c.protocol||'SCA')+' · '+((c.samples||[]).length)+' sample'+((c.samples||[]).length===1?'':'s'),data:{protocol:c.protocol||'SCA',at:c.at,samples:(c.samples||[]).map(s=>({name:s.roastLabel||s.label||'Sample',total:s.total!=null?r1(s.total):null,notes:s.notes||s.descriptors||'',restDays:s.restDays!=null?r1(s.restDays):null}))}}}
function procSnap(p,A){const hs=(p.harvestIds||[]).map(id=>(A.harvest||[]).find(h=>h.id===id)).filter(Boolean);const plots=[...new Set(hs.flatMap(h=>h.plotIds||[]))].map(id=>(A.plot||[]).find(x=>x.id===id)).filter(Boolean);
 const hrs=(a,b)=>{if(!a||!b)return null;const h=(new Date(b)-new Date(a))/36e5;return h>=0?r1(h):null};
 return{title:(p.code||'Process')+' · '+(p.pathway||''),data:{pathway:p.pathway,started:p.started,varieties:[...new Set(plots.map(x=>x.variety).filter(Boolean))].join(', '),altitude:plots.map(x=>x.altitude?x.altitude+' '+(x.altUnit||'ft'):'').filter(Boolean).join(', '),steps:(p.steps||[]).map(s=>({type:s.type,method:s.method||'',hours:hrs(s.start,s.end),inKg:s.inKg||'',outKg:s.outKg||'',inoc:s.inoc||'',readings:(s.readings||[]).length,last:(s.readings||[]).slice(-1)[0]||null})),notes:p.notes||''}}}
function roastSnap(r){const ev=(Array.isArray(r.events)?r.events:Object.values(r.events||{})).filter(Boolean);const rd=r.readings||{};const bt=Array.isArray(rd.bean)?rd.bean:[],ex=Array.isArray(rd.exhaust)?rd.exhaust:[];
 const maxT=Math.max(0,...[...ev,...bt,...ex].map(x=>num(x&&x.time)||0),num(r.elapsed)||0);const f=maxT>7200?1/1000:1;const ds=a=>{const s=a.map(x=>({t:Math.round((num(x.time)||0)*f),v:num(x.temp)})).filter(x=>x.v!=null).sort((a,b)=>a.t-b.t);const k=Math.max(1,Math.ceil(s.length/150));return s.filter((_,i)=>i%k===0)};
 const evs=ev.map(x=>({name:x.name,t:Math.round((num(x.time)||0)*f),bean:x.bean,exhaust:x.exhaust})).sort((a,b)=>a.t-b.t);const fc=evs.find(x=>/first crack/i.test(x.name)),drop=evs.find(x=>/drop|end/i.test(x.name));const total=drop?drop.t:(num(r.elapsed)!=null?Math.round(num(r.elapsed)*f):null);
 const g=num(r.greenWeight),rw=num(r.roastedWeight);
 return{title:[r.estate||r.coffeeCode||r.bean||'Roast',r.roastNo?'#'+r.roastNo:''].filter(Boolean).join(' '),data:{coffee:r.estate||r.bean||'',code:r.coffeeCode||'',roastDate:r.roastDate,machine:r.machineName||'',green:g,roasted:rw,loss:g&&rw?r1((g-rw)/g*100):null,charge:r.chargeTemp||'',total,dev:fc&&total?total-fc.t:null,dtr:fc&&total?r1((total-fc.t)/total*100):null,finalColor:r.finalColor||'',events:evs,bean:ds(bt),exhaust:ds(ex)}}}
async function myRoasts(){return await new Promise(ok=>{const q=indexedDB.open('KoffyKraftTemporaryRoastbook');q.onupgradeneeded=e=>{e.target.transaction.abort();ok([])};q.onsuccess=()=>{const db=q.result;if(!db.objectStoreNames.contains('roasts')){db.close();ok([]);return}const t=db.transaction('roasts','readonly').objectStore('roasts').getAll();t.onsuccess=()=>{db.close();ok(t.result||[])};t.onerror=()=>{db.close();ok([])}};q.onerror=()=>ok([])})}
// ---------- rendering ----------
const mmss=s=>s==null?'':Math.floor(s/60)+':'+String(Math.round(s%60)).padStart(2,'0');
function curve(d){if(!d.bean||d.bean.length<3)return '';const all=[...d.bean,...(d.exhaust||[])];const t1=Math.max(...all.map(x=>x.t)),v0=Math.min(...all.map(x=>x.v)),v1=Math.max(...all.map(x=>x.v));const W=320,H=120,X=t=>8+t/t1*(W-16),Y=v=>8+(v1-v)/Math.max(1,v1-v0)*(H-24);
 const pl=(a,c)=>a.length>1?'<polyline fill="none" stroke="'+c+'" stroke-width="2" points="'+a.map(x=>X(x.t)+','+Y(x.v)).join(' ')+'"/>':'';
 return '<svg class="curve" viewBox="0 0 '+W+' '+H+'">'+pl(d.exhaust||[],'#c9a27e')+pl(d.bean,'#8d583b')+(d.events||[]).map(e=>'<line x1="'+X(e.t)+'" x2="'+X(e.t)+'" y1="8" y2="'+(H-16)+'" stroke="#ddd8d0" stroke-dasharray="2 3"/><text x="'+X(e.t)+'" y="'+(H-4)+'" font-size="8" text-anchor="middle" fill="#77716a">'+esc(String(e.name).slice(0,6))+'</text>').join('')+'</svg>'}
function summary(e){const d=e.data||{},rows=[];const add=(k,v)=>{if(v!=null&&v!=='')rows.push([k,v])};
 if(e.kind==='brew'){add('Coffee',d.coffee);add('Method',[d.method,d.brewer].filter(Boolean).join(' · '));add('Recipe',[d.dose?d.dose+' g':'',d.water?d.water+' g water':'',d.ratio?'1:'+d.ratio:''].filter(Boolean).join(', '));add('Grind',[d.grinder,d.grind].filter(Boolean).join(' '));add('Water',[d.waterTemp?d.waterTemp+' °C':'',d.waterType].filter(Boolean).join(', '));add('Time',d.time);add('Strength',[d.tds?d.tds+'% TDS':'',d.ey?d.ey+'% extraction':''].filter(Boolean).join(', '));add('Rest',d.restDays!=null?d.restDays+' days':'');add('Rating',d.rating?d.rating+' / 10':'');add('Tasted',d.descriptors);add('Notes',d.notes)}
 if(e.kind==='roast'){add('Coffee',[d.coffee,d.code].filter(Boolean).join(' · '));add('Date',d.roastDate);add('Machine',d.machine);add('Weights',[d.green?d.green+' g green':'',d.roasted?d.roasted+' g roasted':'',d.loss?d.loss+'% loss':''].filter(Boolean).join(', '));add('Time',[d.total?mmss(d.total)+' total':'',d.dev?mmss(d.dev)+' development':'',d.dtr?d.dtr+'% DTR':''].filter(Boolean).join(', '));add('Colour',d.finalColor)}
 if(e.kind==='cupping'){add('Form',d.protocol);add('Date',d.at?fmtD(d.at):'');(d.samples||[]).forEach(s=>add(s.name,[s.total!=null?s.total+' pts':'',s.notes].filter(Boolean).join(' · ')))}
 if(e.kind==='process'){add('Pathway',d.pathway);add('Variety',d.varieties);add('Altitude',d.altitude);(d.steps||[]).forEach(s=>add(s.type,[s.method,s.hours!=null?s.hours+' h':'',s.inKg&&s.outKg?s.inKg+' → '+s.outKg+' kg':'',s.inoc].filter(Boolean).join(' · ')));add('Notes',d.notes)}
 if(e.kind==='green'){add('Lot',[d.code,d.name].filter(Boolean).join(' · '));add('Process',d.pathway);add('Variety',d.varieties);add('Altitude',d.altitude);add('Quality',[d.grade,d.screen?'screen '+d.screen:'',d.moisture?d.moisture+'% moisture':'',d.aw?'aw '+d.aw:'',d.density?d.density+' g/L':''].filter(Boolean).join(', '));add('Cup score',d.score);add('Weight',d.kg?d.kg+' kg':'');add('Date',d.date)}
 if(e.kind==='note')add('',d.text);
 return '<div class="kv">'+rows.map(([k,v])=>'<span>'+esc(k)+'</span><div>'+esc(v)+'</div>').join('')+'</div>'+(e.kind==='roast'?curve(d):'')}
function greenSnap(g,A){const pr=(A.process||[]).find(p=>p.id===g.processId);const ps=pr?procSnap(pr,A).data:{};return{title:(g.code||'Green lot')+(g.name?' · '+g.name:''),data:{code:g.code||'',name:g.name||'',pathway:ps.pathway||'',varieties:ps.varieties||'',altitude:ps.altitude||'',kg:num(g.weightKg),moisture:num(g.moisture),aw:num(g.aw),density:num(g.density),screen:g.screen||'',grade:g.grade||'',score:num(g.score),date:g.date||''}}}
