const CACHE='koffykraft-roastbooks-v69';
const CORE=['./roastbooks.html','./koffykraft-wordmark.png','./koffykraft-db.js','./roastbook.html','./roast-timer-v14.html','./roast-graph.html','./roasts.html','./capture.html','./ocr.html','./data.html','./manifest.webmanifest','./koffykraft-icon.svg','./icon-192.png','./icon-512.png','./apple-touch-icon.png','./origin.html','./origin-db.js','./cup.html','./kk.css','./prefs.js','./cloud-ui.js','./water.html','./license.html','./LICENSE','./pv.js','./varieties.js','./colour.js','./brewkb.js','./methods.html','./crop.html','./map.html','./tap.js','./home.html','./contents.html','./contents.js','./journey.html','./feedback.js','./export.js','./share.html','./profile.html','./snap.js'];
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(CORE.map(u=>new Request(u,{cache:'reload'})))).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
// Fast and offline-first: answer from the cache at once, refresh the cache in the background.
// API calls and other sites are never touched here.
async function clean(r){if(!r||!r.redirected)return r;const b=await r.blob();return new Response(b,{status:r.status,statusText:r.statusText,headers:r.headers})}
function refresh(req,key){return fetch(req,{cache:'no-store'}).then(async r=>{if(r&&r.ok){const c=await clean(r.clone());const cache=await caches.open(CACHE);await cache.put(key||req,c)}return r})}
self.addEventListener('fetch',e=>{const req=e.request;if(req.method!=='GET')return;const u=new URL(req.url);if(u.origin!==location.origin||u.pathname.startsWith('/api/'))return;
 if(req.mode==='navigate'){const key=new Request(u.origin+u.pathname);e.respondWith((async()=>{const hit=await caches.match(key,{ignoreSearch:true})||await caches.match(u.pathname.endsWith('.html')?u.pathname:u.pathname+'.html',{ignoreSearch:true});const old=hit?await hit.clone().text().catch(()=>''):'';const net=refresh(u.origin+u.pathname,key).catch(()=>null);if(hit){e.waitUntil(net.then(async r=>{if(!r||!r.ok)return;const t=await r.clone().text().catch(()=>old);if(t===old)return;const id=e.resultingClientId||e.clientId;for(let i=0;i<20;i++){const c=id&&await self.clients.get(id);if(c){c.postMessage({kk:'updated'});return}await new Promise(z=>setTimeout(z,250))}}));return clean(hit)}const r=await net;return r?clean(r):(await caches.match('./roastbooks.html'))||Response.error()})());return}
 e.respondWith((async()=>{const hit=await caches.match(req,{ignoreSearch:true});const net=refresh(req).catch(()=>null);if(hit){e.waitUntil(net);return hit}const r=await net;return r||Response.error()})())});
