const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const j=(v,s=200)=>new Response(JSON.stringify(v),{status:s,headers:JSON_HEADERS});
function bearer(r){const h=r.headers.get("authorization")||"";return h.startsWith("Bearer ")?h.slice(7):""}
async function digest(s){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function user(r,e){const t=bearer(r);if(!t)return null;const h=await digest(t);return await e.DB.prepare("SELECT u.id,u.email,u.display_name FROM auth_sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>datetime('now')").bind(h).first()}
async function body(r){try{return await r.json()}catch{return {}}}
function token(){const a=new Uint8Array(32);crypto.getRandomValues(a);return [...a].map(x=>x.toString(16).padStart(2,"0")).join("")}
export default{async fetch(r,e){const u=new URL(r.url),p=u.pathname;
 if(p==="/"||p==="/index.html"){const a=new URL(r.url);a.pathname="/roastbooks.html";return e.ASSETS.fetch(new Request(a,r))}
 if(!p.startsWith("/api/"))return e.ASSETS.fetch(r);
 if(r.method==="GET"&&p==="/api/status"){let database=false;try{await e.DB.prepare("SELECT 1 AS ok").first();database=true}catch{}return j({ok:true,email_login:Boolean(e.AUTH_EMAIL_ENDPOINT),database})}
 if(r.method==="POST"&&p==="/api/auth/request"){const b=await body(r),email=String(b.email||"").trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))return j({error:"valid email required"},400);const id=crypto.randomUUID(),code=String(Math.floor(100000+Math.random()*900000)),ch=await digest(code);let row=await e.DB.prepare("SELECT id FROM users WHERE email=? LIMIT 1").bind(email).first();if(!row){await e.DB.prepare("INSERT INTO users(id,email,created_at) VALUES(?,?,CURRENT_TIMESTAMP)").bind(id,email).run();row={id}};await e.DB.prepare("DELETE FROM auth_codes WHERE email=? OR expires_at<=datetime('now')").bind(email).run();await e.DB.prepare("INSERT INTO auth_codes(id,email,user_id,code_hash,expires_at) VALUES(?,?,?,?,datetime('now','+10 minutes'))").bind(crypto.randomUUID(),email,row.id,ch).run();if(!e.AUTH_EMAIL_ENDPOINT)return j({error:"email delivery not configured"},503);const resp=await fetch(e.AUTH_EMAIL_ENDPOINT,{method:"POST",headers:{"content-type":"application/json","authorization":"Bearer "+e.AUTH_EMAIL_SECRET},body:JSON.stringify({to:email,subject:"KoffyKraft sign-in code",text:"Your KoffyKraft sign-in code is "+code+". It expires in 10 minutes."})});return resp.ok?j({ok:true}):j({error:"email delivery failed"},502)}
 if(r.method==="POST"&&p==="/api/auth/verify"){const b=await body(r),email=String(b.email||"").trim().toLowerCase(),ch=await digest(String(b.code||""));const a=await e.DB.prepare("SELECT * FROM auth_codes WHERE email=? AND code_hash=? AND expires_at>datetime('now')").bind(email,ch).first();if(!a)return j({error:"invalid or expired code"},401);const t=token(),th=await digest(t);await e.DB.batch([e.DB.prepare("DELETE FROM auth_codes WHERE email=?").bind(email),e.DB.prepare("INSERT INTO auth_sessions(id,user_id,token_hash,expires_at) VALUES(?,?,?,datetime('now','+30 days'))").bind(crypto.randomUUID(),a.user_id,th)]);return j({token:t,user_id:a.user_id})}
 const me=await user(r,e);if(!me)return j({error:"authentication required"},401);
 if(r.method==="GET"&&p==="/api/me")return j({user:me});
 if(r.method==="POST"&&p==="/api/logout"){const h=await digest(bearer(r));await e.DB.prepare("DELETE FROM auth_sessions WHERE token_hash=?").bind(h).run();return j({ok:true})}
 if(r.method==="GET"&&p==="/api/processes"){const q=await e.DB.prepare("SELECT id,name,process_type,scope,created_at,updated_at FROM process_templates WHERE owner_user_id=? ORDER BY updated_at DESC LIMIT 500").bind(me.id).all();return j({items:q.results})}
 if(r.method==="POST"&&p==="/api/processes"){const b=await body(r),id=crypto.randomUUID(),name=String(b.name||"").trim();if(!name)return j({error:"name required"},400);await e.DB.prepare("INSERT INTO process_templates(id,owner_user_id,name,process_type,description,scope) VALUES(?,?,?,?,?,'private')").bind(id,me.id,name,b.process_type||null,b.description||null).run();return j({id,privacy:"private"},201)}
 if(r.method==="POST"&&p==="/api/share"){const b=await body(r),type=String(b.object_type||""),id=String(b.object_id||"");const allowed={process:"process_templates",roast:"roast_runs",brew:"brew_recipes"};if(!allowed[type])return j({error:"unsupported object"},400);const own=await e.DB.prepare("SELECT id FROM "+allowed[type]+" WHERE id=? AND owner_user_id=?").bind(id,me.id).first();if(!own)return j({error:"not found"},404);const st=token();await e.DB.prepare("INSERT INTO shares(id,owner_user_id,object_type,object_id,share_key,permission) VALUES(?,?,?,?,?,'view')").bind(crypto.randomUUID(),me.id,type,id,st).run();return j({share_key:st,permission:"view"},201)}
 if(r.method==="POST"&&p==="/api/roasts"){const b=await body(r),id=b.id||"roast-"+Date.now(),{roasteryName,machineName,estate,bean,coffeeCode,roastNo,moisture,greenWeight,chargeTemp,targetColor,roastedWeight,finalColor,roastDate,unit,elapsed,events,readings}=b;if(!id)return j({error:"roast id required"},400);const eventJson=JSON.stringify(events||[]),readingJson=JSON.stringify(readings||{exhaust:[],bean:[]});await e.DB.prepare("INSERT INTO roast_runs(id,owner_user_id,roast_date,roast_no,roast_type,green_weight,roasted_weight,moisture,charge_temp,target_color,final_color,equipment_id,notes,event_json,reading_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)").bind(id,me.id,roastDate||new Date().toISOString().slice(0,10),roastNo||"1",targetColor||"",greenWeight||null,roastedWeight||null,moisture||null,chargeTemp||null,targetColor||"",finalColor||"",machineName||null,bean||coffeeCode||"",eventJson,readingJson).run();return j({id,saved:true},201)}
 if(r.method==="GET"&&p==="/api/roasts"){const q=await e.DB.prepare("SELECT id,roast_date,roast_no,roast_type,green_weight,roasted_weight,moisture,charge_temp,target_color,final_color,notes,created_at FROM roast_runs WHERE owner_user_id=? ORDER BY roast_date DESC,created_at DESC LIMIT 500").bind(me.id).all();return j({items:q.results||[]})}
 if(r.method==="GET"&&p.match(/^\/api\/roasts\/[^\/]+$/)){const id=p.split("/").pop(),row=await e.DB.prepare("SELECT * FROM roast_runs WHERE id=? AND owner_user_id=?").bind(id,me.id).first();if(!row)return j({error:"not found"},404);return j({...row,events:JSON.parse(row.event_json||"[]"),readings:JSON.parse(row.reading_json||"{exhaust:[],bean:[]}")})}
 return j({error:"not found"},404)
}}