const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const j=(v,s=200)=>new Response(JSON.stringify(v),{status:s,headers:JSON_HEADERS});
function bearer(r){const h=r.headers.get("authorization")||"";return h.startsWith("Bearer ")?h.slice(7):""}
async function digest(s){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function user(r,e){const t=bearer(r);if(!t)return null;const h=await digest(t);return await e.DB.prepare("SELECT u.id,u.email,u.display_name FROM auth_sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>datetime('now')").bind(h).first()}
async function body(r){try{return await r.json()}catch{return {}}}
function token(){const a=new Uint8Array(32);crypto.getRandomValues(a);return [...a].map(x=>x.toString(16).padStart(2,"0")).join("")}
function emailConfigured(e){return Boolean(e.RESEND_API_KEY||(e.AUTH_EMAIL_ENDPOINT&&e.AUTH_EMAIL_SECRET))}
async function sendEmail(e,to,subject,text){try{if(e.RESEND_API_KEY){const resp=await fetch("https://api.resend.com/emails",{method:"POST",headers:{"authorization":"Bearer "+e.RESEND_API_KEY,"content-type":"application/json"},body:JSON.stringify({from:e.AUTH_EMAIL_FROM||"KoffyKraft <onboarding@resend.dev>",to:[to],subject,text})});if(!resp.ok)console.error("resend send failed",resp.status,await resp.text());return{ok:resp.ok}}const form=new URLSearchParams({to,from:e.AUTH_EMAIL_FROM||"KoffyKraft <mailgun@sandboxb97fe0c72adc4feea556292b5ff5f544.mailgun.org>",subject,text});const resp=await fetch(e.AUTH_EMAIL_ENDPOINT,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded","authorization":"Basic "+btoa("api:"+e.AUTH_EMAIL_SECRET)},body:form.toString()});if(!resp.ok)console.error("mailgun send failed",resp.status,await resp.text());return{ok:resp.ok}}catch(err){console.error("email send error",err);return{ok:false}}}
export default{async fetch(r,e){const u=new URL(r.url),p=u.pathname;
 if(p==="/"||p==="/index.html"){const a=new URL(r.url);a.pathname="/roasts.html";return e.ASSETS.fetch(new Request(a,r))}
 if(!p.startsWith("/api/"))return e.ASSETS.fetch(r);
 if(r.method==="GET"&&p==="/api/status"){let database=false;try{await e.DB.prepare("SELECT 1 AS ok").first();database=true}catch{}return j({ok:true,email_login:emailConfigured(e),email_provider:e.RESEND_API_KEY?"resend":(e.AUTH_EMAIL_SECRET?"mailgun":"none"),database})}
 if(r.method==="POST"&&p==="/api/auth/request"){const b=await body(r),email=String(b.email||"").trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))return j({error:"valid email required"},400);if(!emailConfigured(e))return j({error:"email delivery not configured"},503);const ip=r.headers.get("cf-connecting-ip")||"",reqId=crypto.randomUUID();try{const lim=await e.DB.prepare("SELECT (SELECT COUNT(*) FROM auth_requests WHERE email=? AND created_at>datetime('now','-1 hour')) AS byEmail,(SELECT COUNT(*) FROM auth_requests WHERE ip=? AND ip<>'' AND created_at>datetime('now','-1 hour')) AS byIp").bind(email,ip).first();if(lim.byEmail>=5||lim.byIp>=20)return j({error:"Too many sign-in requests. Wait an hour and try again."},429);await e.DB.batch([e.DB.prepare("INSERT INTO auth_requests(id,email,ip) VALUES(?,?,?)").bind(reqId,email,ip),e.DB.prepare("DELETE FROM auth_requests WHERE created_at<datetime('now','-1 day')")])}catch(err){console.error("rate limit check failed",err)}const id=crypto.randomUUID(),code=String(100000+(crypto.getRandomValues(new Uint32Array(1))[0]%900000)),ch=await digest(code);let row=await e.DB.prepare("SELECT id FROM users WHERE email=? LIMIT 1").bind(email).first();if(!row){await e.DB.prepare("INSERT INTO users(id,email,created_at) VALUES(?,?,CURRENT_TIMESTAMP)").bind(id,email).run();row={id}};await e.DB.prepare("DELETE FROM auth_codes WHERE email=? OR expires_at<=datetime('now')").bind(email).run();await e.DB.prepare("INSERT INTO auth_codes(id,email,user_id,code_hash,expires_at) VALUES(?,?,?,?,datetime('now','+10 minutes'))").bind(crypto.randomUUID(),email,row.id,ch).run();const subject="KoffyKraft sign-in code: "+code,text="Your KoffyKraft sign-in code is "+code+". It expires in 10 minutes.\n\nIf you did not ask for this, you can ignore this email.";const sent=await sendEmail(e,email,subject,text);if(!sent.ok){try{await e.DB.prepare("DELETE FROM auth_requests WHERE id=?").bind(reqId).run()}catch{}return j({error:"email delivery failed"},502)}return j({ok:true})}
 if(r.method==="POST"&&p==="/api/auth/verify"){const b=await body(r),email=String(b.email||"").trim().toLowerCase(),ch=await digest(String(b.code||""));const a=await e.DB.prepare("SELECT * FROM auth_codes WHERE email=? AND code_hash=? AND expires_at>datetime('now')").bind(email,ch).first();if(!a)return j({error:"invalid or expired code"},401);const t=token(),th=await digest(t);await e.DB.batch([e.DB.prepare("DELETE FROM auth_codes WHERE email=?").bind(email),e.DB.prepare("INSERT INTO auth_sessions(id,user_id,token_hash,expires_at) VALUES(?,?,?,datetime('now','+30 days'))").bind(crypto.randomUUID(),a.user_id,th)]);return j({token:t,user_id:a.user_id})}
 const me=await user(r,e);if(!me)return j({error:"authentication required"},401);
 if(r.method==="GET"&&p==="/api/me")return j({user:me});
 if(r.method==="POST"&&p==="/api/logout"){const h=await digest(bearer(r));await e.DB.prepare("DELETE FROM auth_sessions WHERE token_hash=?").bind(h).run();return j({ok:true})}
 if(r.method==="GET"&&p==="/api/processes"){const q=await e.DB.prepare("SELECT id,name,process_type,scope,created_at,updated_at FROM process_templates WHERE owner_user_id=? ORDER BY updated_at DESC LIMIT 500").bind(me.id).all();return j({items:q.results})}
 if(r.method==="POST"&&p==="/api/processes"){const b=await body(r),id=crypto.randomUUID(),name=String(b.name||"").trim();if(!name)return j({error:"name required"},400);await e.DB.prepare("INSERT INTO process_templates(id,owner_user_id,name,process_type,description,scope) VALUES(?,?,?,?,?,'private')").bind(id,me.id,name,b.process_type||null,b.description||null).run();return j({id,privacy:"private"},201)}
 if(r.method==="POST"&&p==="/api/share"){const b=await body(r),type=String(b.object_type||""),id=String(b.object_id||"");const allowed={process:"process_templates",roast:"roast_runs",brew:"brew_recipes"};if(!allowed[type])return j({error:"unsupported object"},400);const own=await e.DB.prepare("SELECT id FROM "+allowed[type]+" WHERE id=? AND owner_user_id=?").bind(id,me.id).first();if(!own)return j({error:"not found"},404);const st=token();await e.DB.prepare("INSERT INTO shares(id,owner_user_id,object_type,object_id,share_key,permission) VALUES(?,?,?,?,?,'view')").bind(crypto.randomUUID(),me.id,type,id,st).run();return j({share_key:st,permission:"view"},201)}
 if(r.method==="POST"&&p==="/api/roasts"){const b=await body(r),id=String(b.id||"roast-"+Date.now());const num=v=>{const n=parseFloat(v);return Number.isFinite(n)?n:null};const cnt=await e.DB.prepare("SELECT COUNT(*) as cnt FROM roast_runs WHERE owner_user_id=?").bind(me.id).first();if(cnt.cnt>=1000)return j({error:"Roast limit reached. Export and delete old roasts to make room.",quota_exceeded:true,limit:1000,current:cnt.cnt},429);const own=await e.DB.prepare("SELECT owner_user_id FROM roast_runs WHERE id=?").bind(id).first();if(own&&own.owner_user_id!==me.id)return j({error:"roast id already used"},409);const eventJson=JSON.stringify(Array.isArray(b.events)?b.events:[]),readingJson=JSON.stringify(b.readings&&typeof b.readings==="object"?b.readings:{exhaust:[],bean:[]});const details=JSON.stringify({estate:b.estate||"",coffeeCode:b.coffeeCode||"",bean:b.bean||b.notes||"",notes:b.notes||"",roasteryName:b.roasteryName||"",machineName:b.machineName||"",unit:b.unit||"C",elapsed:num(b.elapsed),finishedAt:b.finishedAt||null});try{await e.DB.prepare("INSERT INTO roast_runs(id,owner_user_id,roast_date,roast_number,green_weight,roasted_weight,moisture,charge_temperature,target_color,final_color,notes,events_json,readings_json,ended_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET roast_date=excluded.roast_date,roast_number=excluded.roast_number,green_weight=excluded.green_weight,roasted_weight=excluded.roasted_weight,moisture=excluded.moisture,charge_temperature=excluded.charge_temperature,target_color=excluded.target_color,final_color=excluded.final_color,notes=excluded.notes,events_json=excluded.events_json,readings_json=excluded.readings_json,ended_at=excluded.ended_at").bind(id,me.id,b.roastDate||new Date().toISOString().slice(0,10),String(b.roastNo||""),num(b.greenWeight),num(b.roastedWeight),num(b.moisture),num(b.chargeTemp),b.targetColor||"",b.finalColor||"",details,eventJson,readingJson,b.finishedAt||null).run()}catch(err){return j({error:"save failed: "+String(err&&err.message||err)},500)}return j({id,saved:true},201)}
 if(r.method==="GET"&&p==="/api/roasts"){const q=await e.DB.prepare("SELECT id,roast_date,roast_number,green_weight,roasted_weight,moisture,charge_temperature,target_color,final_color,notes,events_json,readings_json,ended_at,created_at FROM roast_runs WHERE owner_user_id=? ORDER BY roast_date DESC,created_at DESC LIMIT 500").bind(me.id).all();return j({items:q.results||[]})}
 if(r.method==="GET"&&p.match(/^\/api\/roasts\/[^\/]+$/)){const id=p.split("/").pop(),row=await e.DB.prepare("SELECT * FROM roast_runs WHERE id=? AND owner_user_id=?").bind(id,me.id).first();if(!row)return j({error:"not found"},404);return j({...row,events:JSON.parse(row.events_json||"[]"),readings:JSON.parse(row.readings_json||'{"exhaust":[],"bean":[]}')})}
 return j({error:"not found"},404)
}}